name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  push:

  pull_request:

  workflow_dispatch:

  release:
    types: [published]

defaults:
  run:
    shell: bash

jobs:

  shellcheck:
    name: Run Shellcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update packages & install shellcheck
        run: |
          sudo apt-get update -y
          sudo apt-get install shellcheck

      - name: Test ./entrypoint.sh
        run: shellcheck ./entrypoint.sh

  test_conversions:
    name: Test Conversion
    needs: shellcheck
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Default paramaters
        uses: ./ # Uses action in the root directory 
        with:
          INPUT_FILE: '.github/workflows/testfile-in.ai'

      - name: Optional GS + file paramaters
        uses: ./ # Uses action in the root directory
        with:
          INPUT_FILE: '.github/workflows/testfile-in.ai'
          OUTPUT_FILE: 'build/testfile-out.pdf'
          OPTIONAL_PARAMS: '-dCompatibilityLevel=1.4 -dPDFSETTINGS=/printer'

      - name: Optional GS + file paramaters + NO commit
        uses: ./ # Uses action in the root directory
        with:
          INPUT_FILE: '.github/workflows/testfile-in.ai'
          OUTPUT_FILE: 'build/testfile-out-no-commit.pdf'
          GH_CREATE_COMMIT: 'false'
          OPTIONAL_PARAMS: '-dCompatibilityLevel=1.4 -dPDFSETTINGS=/printer'

      - name: Display Results
        run: |
          git show --summary

          echo "Input file:"
          du -h .github/workflows/testfile-in.ai

          echo "Default option file:"
          du -h build/output.pdf

          echo "Output file:"
          du -h build/testfile-out.pdf
